easypoll/easypoll/easypoll/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

easypoll/easypoll/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^createpoll/$', views.CreatePollView.as_view(), name='createpoll'),
    url(r'^error/$', views.ErrorView.as_view(), name='error'),
    url(r'^(?P<question_id>[0-9]+)/$', views.PollView.as_view(), name='poll'),
    url(r'^(?P<question_id>[0-9]+)/results/$',
        views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',
        views.VoteView.as_view(), name='vote'),
]

easypoll/easypoll/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    TYPE_SINGLE = 0
    TYPE_MULTI = 1
    TYPE_CHOICES = (
        (TYPE_SINGLE, 'Single choice'),
        (TYPE_MULTI, 'Multiple choice'),
    )
    # To use for POST data validation
    TYPES_LIST = [v[0] for v in TYPE_CHOICES]

    RESTRICTION_ONE_IP = 0
    RESTRICTION_MANY_IPS = 1
    RESTRICTIONS = (
        (RESTRICTION_ONE_IP, 'Users can vote only once'),
        (RESTRICTION_MANY_IPS, 'Users can vote many times')
    )
    # To use for POST data validation
    RESTRICTIONS_LIST = [v[0] for v in RESTRICTIONS]

    question_text = models.CharField(max_length=200, null=False, blank=False)
    pub_date = models.DateTimeField('date published', null=False, blank=False)
    question_type = models.IntegerField(default=TYPE_SINGLE,
                                        choices=TYPE_CHOICES)
    restriction = models.IntegerField(default=RESTRICTION_ONE_IP,
                                      choices=RESTRICTIONS)
    total_votes = models.IntegerField(default=0)

    def __str__(self):
        return ('id:{0} - {1}'.format(self.id, self.question_text))


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,
                                 null=False, blank=False)
    choice_text = models.CharField(max_length=200, null=False, blank=False)
    votes = models.IntegerField(default=0)

    __original_votes = None

    def __init__(self, *args, **kwargs):
        super(Choice, self).__init__(*args, **kwargs)
        self.__original_votes = self.votes

    def percentage(self):
        if self.question.total_votes == 0:
            return 0
        return round(1000 * self.votes / self.question.total_votes) / 10

    def __str__(self):
        return ('Q:{0} - V:{1} - {2}'.format(self.question.question_text,
                                             self.votes, self.choice_text))

    def save(self, *args, **kwargs):
        # If votes changed
        if (self.votes != self.__original_votes):
            self.question.total_votes += self.votes - self.__original_votes
            self.question.save()
        super(Choice, self).save(*args, **kwargs)
        self.__original_votes = self.votes


class IpAddress(models.Model):
    ip_address_text = models.GenericIPAddressField(
                                protocol='both', unpack_ipv4=True, unique=True,
                                null=False, blank=False)

    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return ('{0} - is blocked:{1}'
                .format(self.ip_address_text, self.is_blocked))


class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,
                                 null=False, blank=False)
    ip_address = models.ForeignKey(IpAddress, on_delete=models.CASCADE,
                                   null=False, blank=False)
    vote_date = models.DateTimeField('date voted', null=False, blank=False)

    class Meta:
        unique_together = ('question', 'ip_address',)

    def __str__(self):
        return str('{0} - {1}'.format(self.question, self.ip_address))

easypoll/easypoll/polls/forms.py
from django import forms
from django.conf import settings
from .models import Question
from captcha.fields import ReCaptchaField
import logging


# Get an instance of a logger
logger = logging.getLogger('root_logger')


# This is a CharField for ContactForm
class PollFormCharField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(PollFormCharField, self).__init__(
                    max_length=settings.MAX_CHOICE_LENGTH,
                    *args, **kwargs)


class NoIdForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(NoIdForm, self).__init__(*args, **dict(kwargs, auto_id=False))


class CaptchaForm(forms.Form):
    captcha = ReCaptchaField()


class PollForm(NoIdForm):

    # Form fields
    question = PollFormCharField()
    choices = PollFormCharField(required=False)
    question_type = forms.ChoiceField(choices=Question.TYPE_CHOICES)
    question_restriction = forms.ChoiceField(choices=Question.RESTRICTIONS)

    def clean(self):
        super(PollForm, self).clean()

        choices = []
        for choice in self.data.getlist('choices'):
            if not choice or choice.isspace():
                continue
            choices.append(choice[:200].strip())
        self.cleaned_data['choices'] = choices

    def is_valid(self):
        is_valid = super(PollForm, self).is_valid()
        choices = self.cleaned_data['choices']
        is_valid = is_valid and len(choices) >= 2
        is_valid = is_valid and len(choices) <= settings.MAX_CHOICES
        return is_valid


class VoteForm(NoIdForm):
    choices = forms.ChoiceField()
    question = None

    def __init__(self, *args, **kwargs):
        try:
            self.question = kwargs.pop('question')
        except KeyError:
            pass
        super(VoteForm, self).__init__(*args, **kwargs)

        if self.question:
            choices = []
            for choice in self.question.choice_set.all():
                choices.append((choice.id, choice.choice_text))
            self.fields['choices'] = forms.ChoiceField(choices=choices)

    def clean(self):
        super(VoteForm, self).clean()

        if not self.question:
            return

        choices = []
        for choice_id in self.data.getlist('choices'):
            try:
                choice_id = int(choice_id)
                choice = self.question.choice_set.get(pk=choice_id)
                choices.append(choice)
            except Exception as e:
                logger.exception(e)
        self.cleaned_data['choices'] = choices

    def is_valid(self):
        if not self.question:
            return False

        if len(self.data.getlist('choices')) > settings.MAX_CHOICES:
            return False

        is_valid = super(VoteForm, self).is_valid()

        choices = self.cleaned_data['choices']

        single = self.question.question_type == Question.TYPE_SINGLE
        # If single
        if single and len(choices) == 1:
                return True and is_valid
        # Else if multi
        elif len(choices) > 0:
                return True and is_valid
        return False

# class ChoicesForm(forms.Form):
#     choices = PollFormCharField()

#     def __init__(self, *args, **kwargs):
#         super(ChoicesForm, self).__init__(*args, **dict(kwargs, auto_id=False))

# ChoicesFormset = forms.formset_factory(ChoicesForm, min_num=1,
#                                        validate_min=True, extra=3)

easypoll/easypoll/polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.utils import timezone
# from ratelimit.decorators import ratelimit
from ratelimit.utils import is_ratelimited
from .models import Question, Choice
from .forms import PollForm, VoteForm, CaptchaForm
from .utils import many_ips_can_vote, IpAddressWrapper
import logging

# Get an instance of a logger
logger = logging.getLogger('root_logger')


# Create your views here.

# Basic class view
class BasicView(View):
    template_name = None


class RateLimitedView(BasicView):
    key = 'ip'
    rate = '1/m'
    group = 'default'
    increment = True

    def check_block(self, request, *args, **kwargs):
        return is_ratelimited(request, key=self.key,
                              group=self.group, rate=self.rate,
                              increment=self.increment)


# Class that has the same behavior against post and get requests
class GetPostView(BasicView):

    # Implementation in subclasses
    def _get_post(self, request, *args, **kwargs):
        pass

    def get(self, request, *args, **kwargs):
        return self._get_post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self._get_post(request, *args, **kwargs)


class CreatePollView(RateLimitedView):
    rate = '5/m'

    def get(self, request):
        return redirect(reverse('polls:index'))

    # Checks if POST request is valid and register vote
    def create_poll(self, cleaned_data):
        question = Question.objects.create(
                        question_text=cleaned_data.get('question'),
                        pub_date=timezone.now(),
                        question_type=cleaned_data.get('question_type'),
                        restriction=cleaned_data.get('question_restriction')
                    )
        # Also create the choices
        for choice in cleaned_data.get('choices'):
            Choice.objects.create(question=question, choice_text=choice)

        return question.id

    def handle_ajax(self, request):
        # Check if ip is blocked

        # Check if ip is blocked
        ip = IpAddressWrapper(request)
        if ip.is_blocked():
            form = CaptchaForm(request.POST)
            if form.is_valid():
                ip.unblock()
            else:
                return JsonResponse({'iserror': True})

        blocked = self.check_block(request)
        if blocked:
            ip.block()

        form = PollForm(request.POST)
        if form.is_valid():
            qid = self.create_poll(form.cleaned_data)
            return JsonResponse({'iserror': False, 'next_url': qid,
                                 'blocked': blocked})
        else:
            return JsonResponse({'iserror': True, 'blocked': blocked})

    def handle_normal(self, request):
        if self.check_block(request):
            ratelimit_error = ErrorView.ratelimit_error
            url = reverse('polls:index')
            return ErrorView.redirect_to_error(url, ratelimit_error)

        form = PollForm(request.POST)
        if form.is_valid():
            qid = self.create_poll(form.cleaned_data)
            return redirect(reverse('polls:poll', args=(qid,)))
        else:
            return ErrorView.redirect_to_error(reverse('polls:index'))

    def post(self, request):
        if request.is_ajax():
            return self.handle_ajax(request)
        else:
            return self.handle_normal(request)


class VoteView(RateLimitedView):
    rate = '10/m'

    def get(self, request, question_id):
        return redirect(reverse('polls:poll',
                                args=(question_id,)))

    # Register the vote, meaning that the client's ip has
    # voted for this question, and add votes
    def register_votes(self, request, form):
        # If not multi vote try to register ip
        # If that fails return False
        check = True
        multi_vote = many_ips_can_vote(form.question)
        if not multi_vote:
            check = IpAddressWrapper(request).register_vote(form.question)
        if not check:
            return False
        # Add votes to choice
        for choice in form.cleaned_data['choices']:
            choice.votes += 1
            choice.save()

        return True

    def check_meta(self, request, question):
        multi_vote = many_ips_can_vote(question)
        voted = IpAddressWrapper(request).has_voted(question)
        check = multi_vote or not voted
        return check

    def handle_ajax(self, request, question_id):
        # Check if ip is blocked
        ip = IpAddressWrapper(request)
        if ip.is_blocked():
            form = CaptchaForm(request.POST)
            if form.is_valid():
                ip.unblock()
            else:
                return JsonResponse({'iserror': True})

        if self.check_block(request):
            ip.block()

        question = get_object_or_404(Question, pk=question_id)
        check = self.check_meta(request, question)
        form = VoteForm(request.POST, question=question)
        check = check and form.is_valid()

        check = check and self.register_votes(request, form)
        if check:
            return JsonResponse({'iserror': False})
        else:
            return JsonResponse({'iserror': True})

    def handle_normal(self, request, question_id):
        if self.check_block(request):
            ratelimit_error = ErrorView.ratelimit_error
            url = reverse('polls:poll', args=(question_id,))
            return ErrorView.redirect_to_error(url, ratelimit_error)

        question = get_object_or_404(Question, pk=question_id)

        check = self.check_meta(request, question)
        form = VoteForm(request.POST, question=question)
        check = check and form.is_valid()
        check = check and self.register_votes(request, form)
        if check:
            return redirect(reverse('polls:results', args=(question.id,)))
        else:
            return redirect(reverse('polls:poll', args=(question.id,)))

    def post(self, request, question_id):
        if request.is_ajax():
            return self.handle_ajax(request, question_id)
        else:
            return self.handle_normal(request, question_id)


# Class to display index page
@method_decorator(never_cache, name='get')
@method_decorator(never_cache, name='post')
class IndexView(GetPostView):
    template = 'polls/index.html'

    def _get_post(self, request):
        form = PollForm()
        blocked = IpAddressWrapper(request).is_blocked()
        return render(request, self.template,
                      {'form': form, 'blocked': blocked})


# Class to display poll
@method_decorator(never_cache, name='get')
@method_decorator(never_cache, name='post')
class PollView(GetPostView):
    template = 'polls/poll.html'

    def _get_post(self, request, question_id=None):
        # If question does not exist return 404
        question = get_object_or_404(Question, pk=question_id)
        # If many ips can vote or the user has not voted for this poll
        # set can_vote to True else False
        can_vote = (many_ips_can_vote(question) or
                    not IpAddressWrapper(request).has_voted(question))
        form = VoteForm(question=question)
        blocked = IpAddressWrapper(request).is_blocked()
        return render(request, self.template, {
                       'question': question, 'can_vote': can_vote,
                       'type': Question.TYPE_CHOICES, 'form': form,
                       'blocked': blocked
                    })


# Class to display results
class ResultsView(GetPostView):
    template = 'polls/results.html'

    def _get_post(self, request, question_id=None):
        question = get_object_or_404(Question, pk=question_id)
        return render(request, self.template, {'question': question})


# Class to display an error
class ErrorView(GetPostView):
    template = 'polls/error.html'
    default_error = 0
    ratelimit_error = 1

    def construct_error_url(url, error=None):
        if error is None:
            error = ErrorView.default_error
        final_url = reverse('polls:error')
        final_url += "?%s%s" % ('next=', url)
        final_url += "&%s%s" % ('error=', error)
        return final_url

    def redirect_to_error(url, error=None):
        final_url = ErrorView.construct_error_url(url, error)
        return HttpResponseRedirect(final_url)

    def _get_post(self, request):
        nxt = request.GET.get('next', default=reverse('polls:index'))
        error = request.GET.get('error', default=self.default_error)
        return render(request, self.template, {'next': nxt, 'error': error})

easypoll/easypoll/polls/templates/polls/error.html
<!DOCTYPE HTML>
{% load static %}
{% load compress %}
<html>

<head>
    <title>Error</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'polls/error/style.scss' %}">
    {% endcompress %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" 
	        	language="Javascript" 
	        	type="text/javascript">
	</script>

    <script type="text/javascript">
        if (typeof jQuery == 'undefined') {
            document.write(unescape("%3Cscript src='{% static 'polls/jquery-2.2.0.min.js' %}' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>

    {% compress js %}
    <script src="{% static 'polls/error/error.js' %}" 
	        	language="Javascript" 
	        	type="text/javascript">
    </script>
    {% endcompress js %}

</head>
<body>
	<div id="header">
		<a id="header-title" href="{% url 'polls:index' %}">SimplePoll</a>
	</div>
	<div class="notebook-wrapper">
		<div class="notebook">
			<div class="error-message">
            {% if error == '1' %}
                Chief cool down. <a href="{{ next }}">Try again</a> in a minute.
            {% else %}
                Something went wrong please <a href="{{ next }}">try again!</a>
            {% endif %}
			</div>
		</div>
	</div>
    <div id="footer">
    	<!-- <img src="https://www.djangoproject.com/s/img/badges/djangopowered126x54.gif" /> -->
    </div>
</body>
</html>

easypoll/easypoll/polls/templates/polls/index.html
<!DOCTYPE HTML>
{% load static %}
{% load compress %}
{% load widget_tweaks %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create a poll</title>
            
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'polls/index/style.scss' %}">
    {% endcompress %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" 
            language="Javascript" 
            type="text/javascript">
    </script>

    <script type="text/javascript">
        if (typeof jQuery == 'undefined') {
            document.write(unescape("%3Cscript src='{% static 'polls/jquery-2.2.0.min.js' %}' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js?onload=captchaLoaded&render=explicit" async defer></script>
    {% compress js %}
    <script src="{% static 'polls/index/index.js' %}" 
            language="Javascript" 
            type="text/javascript">
    </script>
    {% endcompress %}

</head>
<body>

    <noscript>
        <div id="no-js-warning-wrapper" class="no-js">
            <div id="no-js-warning-container">
                It appears you are not using Javascript. Site functionality is limited. You can only select up to 4 options per poll.
            </div>
        </div>
    </noscript>
    <div id="header">
        <a id="header-title" href="{% url 'polls:index' %}">SimplePoll</a>
    </div>
    <div class="notebook-wrapper">
    <div class="notebook">
        <form id="poll-form" action="{% url 'polls:createpoll' %}" method="post">
            {% csrf_token %}
            <div id="choices-container">
                {% render_field form.question id='question' placeholder='Enter your question...' autocomplete='off' required='required' pattern='.*\S+.*' %}
                <div class="new-line"></div>

                {% render_field form.choices autocomplete='off' placeholder='Enter an option... ' pattern='.*\S+.*' required='required' %}

                {% render_field form.choices autocomplete='off' placeholder='Enter an option... ' required='required' %}
                
                {% render_field form.choices autocomplete='off' placeholder='Enter an option... ' %}

                {% render_field form.choices autocomplete='off' placeholder='Enter an option... ' %}

            </div>
            <div class="question-options">
                {{ form.question_type }}
            </div>
            <div class="question-options">
                {{ form.question_restriction }}
            </div>
            {% if blocked %}
                <input type='hidden' id="blocked" />
            {% endif %}
                <!-- {{ form.captcha }} -->
            <div class="g-recaptcha"></div>
            <input type="Submit" id="submit" value="Create poll"/>
        </form>
    </div>
    </div>
    <div id="popup-wrapper">
        <div id="popup-container">
            <div id="hide-button-container">
                <button id="hide-button">&#10006;</button>
            </div>
            <div id="popup-content"></div>
            <div id="poll-url-container">
                <div id="poll-url" title="Click to redirect!"></div>
            </div>
            <div id="popup-ok-button-container">
                <button id="popup-ok-button">OK</button>
            </div>
        </div>
    </div>
    <div id="fade"></div>
    <div id="footer">
        <!-- <img src="https://www.djangoproject.com/s/img/badges/djangopowered126x54.gif" /> -->
    </div>
</body>
</html>

easypoll/easypoll/polls/templates/polls/poll.html
<!DOCTYPE HTML>
{% load static %}
{% load compress %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vote for "{{ question.question_text }}"</title>
    
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'polls/poll/style.scss' %}">
    {% endcompress %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" 
	        	language="Javascript" 
	        	type="text/javascript">
	</script>

    <script type="text/javascript">
        if (typeof jQuery == 'undefined') {
            document.write(unescape("%3Cscript src='{% static 'polls/jquery-2.2.0.min.js' %}' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>
	<script src="https://www.google.com/recaptcha/api.js?onload=captchaLoaded&render=explicit" async defer></script>
    {% compress js %}
    <script src="{% static 'polls/poll/poll.js' %}" 
		        	language="Javascript" 
		        	type="text/javascript">
	</script>
    {% endcompress %}
</head>

<body>
	<noscript>
		<div id="no-js-warning-wrapper" class="no-js">
			<div id="no-js-warning-container">
				It appears you are not using Javascript. Site functionality is limited. To vote please select one (single-choice) or more (multi-choice) options to proceed.
			</div>
		</div>
	</noscript>
	<div id="header">
		<a id="header-title" href="{% url 'polls:index' %}">SimplePoll</a>
	</div>
	<div class="notebook-wrapper">
		<div class="notebook">
			<form id="vote-form" action="{% url 'polls:vote' question.id %}" method="post">
				{% csrf_token %}
			    <div class="question">{{ question.question_text }}</div>
			    <div class="question-type">({{ question.get_question_type_display }})</div>
			    <div class="new-line"></div>
			    {% if question.question_type == question.TYPE_MULTI %}
		        <div class="checkbox">
				    {% for id, val in form.fields.choices.choices %}
				    <div class="entry">
			            <input type="checkbox" name="choices" id="{{ id }}" value="{{ id }}" {% if not can_vote %} disabled {% endif %}/>
			            <label for="{{ id }}">{{ val }}</label>
			            
		            </div>
					{% endfor %}
				</div>
		        {% else %}
		        <div class="radio">
		        	{% for id, val in form.fields.choices.choices %}
				    <div class="entry">
			            <input type="radio" name="choices" id="{{ id }}" value="{{ id }}" {% if not can_vote %} disabled {% endif %}/>
			            <label for="{{ id }}">{{ val }}</label>
			            
		            </div>
					{% endfor %}
				</div>
				{% endif %}
			    {% if not blocked %}
			    	<div class="new-line"></div>
                {% endif %}
                {% if blocked and can_vote %}
                	<input type='hidden' id="blocked" />
            	{% endif %}
            	<div class="g-recaptcha"></div>
			    <div id="submit-div">
					<input {% if not can_vote %} disabled {% endif %} type="Submit" value="Vote"/>
					<div id="space-submit"></div>
					<a id="results-button" value="Results" href="{% url 'polls:results' question.id %}">Results</a>
				</div>
				{% if not can_vote %}
				<div class="message">You have already voted!</div>
				{% endif %}
			</form>
		</div>
	</div>

    <div id="popup-wrapper">
    	<div id="popup-container">
    		<div id="popup-content"></div>
    		<div id="popup-ok-button-container">
    			<button id="popup-ok-button">OK</button>
    		</div>
    	</div>
    </div>
    <div id="fade"></div>
    <div id="footer">
    	<!-- <img src="https://www.djangoproject.com/s/img/badges/djangopowered126x54.gif" /> -->
    </div>
</body>
</html>

easypoll/easypoll/polls/templates/polls/results.html
<!DOCTYPE HTML>
{% load static %}
{% load compress %}
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Poll results</title>
    
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'polls/results/style.scss' %}">
    {% endcompress %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" 
                language="Javascript" 
                type="text/javascript">
    </script>

    <script type="text/javascript">
        if (typeof jQuery == 'undefined') {
            document.write(unescape("%3Cscript src='{% static 'polls/jquery-2.2.0.min.js' %}' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>

     <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    {% compress js %}
    <script src="{% static 'polls/results/colors.js' %}" 
          language="Javascript" 
          type="text/javascript">
    </script>

    <script src="{% static 'polls/results/throttledresize.js' %}" 
          language="Javascript" 
          type="text/javascript">
    </script>

    <script src="{% static 'polls/results/results.js' %}" 
          language="Javascript" 
          type="text/javascript">
    </script>
    {% endcompress %}
</head>

<body>
    <noscript>
        <div id="no-js-warning-wrapper" class="no-js">
            <div id="no-js-warning-container">
                It appears you are not using Javascript. Site functionality is limited. You will not be able to see a graph representation for the results.
            </div>
        </div>
    </noscript>

    <div id="header">
        <a id="header-title" href="{% url 'polls:index' %}">SimplePoll</a>
    </div>
    <div class="notebook-wrapper">
        <div id="choices-data-container" class="notebook">
            <div class="question">{{ question.question_text }}</div>
            <div class="new-line"></div>
            {% for choice in question.choice_set.all %}
            <div class='entry'>
                <div class="choice" value="{{ choice.choice_text }}">{{ choice.choice_text }}</div>
                <div class="meter-container">
                    <div class="meter">
                        <div class="bar" style="width: {{ choice.percentage }}%"></div>
                    </div>
                    <div class="votes" value="{{ choice.votes }}">{{ choice.votes }} vote{{ choice.votes|pluralize }} ({{ choice.percentage }}%)</div>
                </div>  
            </div>
            {% endfor %}
        </div>

        <div id="chart-data-container" class="notebook">
            <div id="chart-title"> {{ question.question_text }} (Graph)</div>
            <div id="chart-wrapper">
                <div id="chart"></div>
            </div>
        </div>
    </div>
    <div id="footer">
        <!-- <img src="https://www.djangoproject.com/s/img/badges/djangopowered126x54.gif" /> -->
    </div>
</body>

</html>